; =============================================
; JOGO DA VELHA - ASSEMBLY x86
; Versão mesclada: organização do código 2 + IA funcional do código 1
; =============================================

TITLE Jogo da Velha
.MODEL SMALL
.STACK 100H

;-------------- DECLARAÇÃO DE MACROS ------------
TESTA_CASA_IA MACRO CASA      ; MACRO FUNCIONAL DO CÓDIGO 1
      LOCAL VALOR_X
      LOCAL VALOR_O
      LOCAL SAI
      CMP CASA, 'X'           ; É X?
      JE VALOR_X
      CMP CASA, 'O'           ; É O?
      JE VALOR_O
      JMP SAI
      VALOR_X:
      INC DL                  ; Incrementa contador de X
      JMP SAI
      VALOR_O:
      INC DH                  ; Incrementa contador de O
      SAI:
      ENDM

.DATA
    COR_VERDE EQU 2
    MODO_TEXTO EQU 3

    ; Elementos de interface
    LinhaSeparadora DB "    +-------------------------------------+", 10, 13, '$'
    Titulojogo      DB "    |      BEM-VINDO AO JOGO DA VELHA     |", 10, 13, '$'
    Opcao1v1        DB "    |   [1] - Jogador X Jogador           |", 10, 13, '$'
    Opcap1vIA       DB "    |   [2] - Jogador X IA                |", 10, 13, '$'
    Opcaosaida      DB "    |   [0] - Sair do Jogo                |", 10, 13, '$'
    LinhaVazia      DB "    |                                     |", 10, 13, '$'

    ; Estado do jogo
    MATRIZ         DB  '1','2','3','4','5','6','7','8','9'
    JOGADOR_ATUAL  DB 'X'              ; Começa com jogador X
    JOGADAS_FEITAS DB 0                ; Contador para detectar empate

    ; Mensagens do sistema
    TURNO          DB 10, 13, "Agora eh o turno do jogador ", 0, 10, 13, 'Escolha uma casa!', 10, 13,'$'
    NUMEROINVALIDO DB 10, 13, "Numero invalido. Escolha outra.", 10, 13, '$'
    CASAOCUPADA    DB 10, 13, "Casa ocupada. Escolha outra.", 10, 13, '$'
    Vitoria        DB "Vitoria do jogador ", 0, '!', 10, 13, '$'
    Empate         DB "Empate! Boa sorte na proxima!$"
    CLIQUE         DB "Pressione ENTER para voltar ao menu...$'

.CODE
MAIN PROC 
    MOV AX, @DATA        ; Inicializa segmento de dados
    MOV DS, AX

MAIN_LOOP:
    CALL LIMPAR_REGISTRADORES
    CALL IMPRIMIR_TELA_INICIAL
    CALL LER_ESCOLHA_USUARIO
    
    CMP AL, 0
    JE FIM_PROGRAMA
    CMP AL, 1
    JE INICIAR_PVP
    CMP AL, 2
    JE INICIAR_PVIA
    JMP MAIN_LOOP

INICIAR_PVP:
    CALL JOGO_PVP
    JMP MAIN_LOOP

INICIAR_PVIA:
    CALL JOGO_PV_IA
    JMP MAIN_LOOP

FIM_PROGRAMA:
    MOV AH, 4CH
    INT 21H
MAIN ENDP

; ========== PROCEDIMENTOS DE UTILIDADE ==========
LIMPAR_REGISTRADORES PROC
    XOR AX, AX
    XOR DX, DX  
    XOR BX, BX
    XOR CX, CX
    RET
LIMPAR_REGISTRADORES ENDP

LER_ESCOLHA_USUARIO PROC
    MOV AH, 1
    INT 21H
    AND AL, 0FH
    RET
LER_ESCOLHA_USUARIO ENDP

; ========== PROCEDIMENTOS DE INTERFACE ==========
IMPRIMIR_TELA_INICIAL PROC
    PUSH AX
    PUSH BX 
    PUSH CX
    PUSH DX

    CALL CONFIGURAR_TELA
    MOV AH, 9
    
    LEA DX, LinhaSeparadora
    INT 21H
    LEA DX, LinhaVazia
    INT 21H
    LEA DX, Titulojogo
    INT 21H
    LEA DX, LinhaVazia
    INT 21H
    LEA DX, LinhaSeparadora
    INT 21H
    LEA DX, LinhaVazia
    INT 21H
    LEA DX, Opcao1v1
    INT 21H
    LEA DX, LinhaSeparadora
    INT 21H
    LEA DX, LinhaVazia
    INT 21H
    LEA DX, Opcap1vIA
    INT 21H
    LEA DX, LinhaSeparadora
    INT 21H
    LEA DX, LinhaVazia
    INT 21H
    LEA DX, Opcaosaida
    INT 21H
    LEA DX, LinhaSeparadora
    INT 21H

    POP DX
    POP CX
    POP BX
    POP AX
    RET
IMPRIMIR_TELA_INICIAL ENDP

CONFIGURAR_TELA PROC
    MOV AH, 0
    MOV AL, MODO_TEXTO
    INT 10H
    MOV AH, 0BH
    MOV BH, 0
    MOV BL, COR_VERDE
    INT 10H
    RET
CONFIGURAR_TELA ENDP

IMPRIMIR_TABULEIRO PROC
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX
    PUSH SI

    CALL CONFIGURAR_TELA
    MOV AH, 2
    XOR CX, CX
    XOR BX, BX

IMPRIMIR_LINHA_TAB:
    MOV CX, 19
    MOV DL, ' '
    
IMPRIMIR_ESPACOS_TAB:
    INT 21H
    LOOP IMPRIMIR_ESPACOS_TAB
    
    MOV CX, 3
    XOR SI, SI

IMPRIMIR_COLUNA_TAB:
    MOV DL, MATRIZ[BX][SI]
    INT 21H
    CMP SI, 2
    JE PROXIMA_LINHA_TAB
    MOV DL, ' '
    INT 21H
    MOV DL, '|'
    INT 21H
    MOV DL, ' '
    INT 21H
    INC SI
    LOOP IMPRIMIR_COLUNA_TAB
    
PROXIMA_LINHA_TAB:
    MOV DL, 10
    INT 21H
    ADD BX, 3
    CMP BX, 6
    JBE IMPRIMIR_LINHA_TAB
    
    POP SI
    POP DX
    POP CX
    POP BX
    POP AX
    RET
IMPRIMIR_TABULEIRO ENDP

EXIBIR_RESULTADO_FINAL PROC
    CALL IMPRIMIR_TABULEIRO
    CMP CL, 2
    JE EXIBIR_EMPATE

    MOV AH, 9
    MOV AL, JOGADOR_ATUAL
    MOV BX, 19
    MOV [Vitoria+BX], AL
    LEA DX, Vitoria
    INT 21H
    JMP FINALIZAR_EXIBICAO

EXIBIR_EMPATE:
    MOV AH, 9
    LEA DX, Empate
    INT 21H

FINALIZAR_EXIBICAO:
    RET
EXIBIR_RESULTADO_FINAL ENDP

; ========== MODO PLAYER VS PLAYER ==========
JOGO_PVP PROC
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX
    PUSH SI
    
CICLO_PVP:
    CALL IMPRIMIR_TABULEIRO
    CALL EXIBIR_TURNO_ATUAL
    CALL LER_JOGADA
    CALL VALIDAR_JOGADA
    JC JOGADA_INVALIDA_PVP

    CALL ATUALIZAR_MATRIZ
    CALL VERIFICAR_ESTADO_JOGO
    TEST CL, CL
    JZ CONTINUAR_PVP
    CALL EXIBIR_RESULTADO_FINAL
    JMP FINALIZAR_PVP

CONTINUAR_PVP:
    CALL ALTERNAR_JOGADOR
    JMP CICLO_PVP

JOGADA_INVALIDA_PVP:
    CALL TRATAR_ERRO_JOGADA
    JMP CICLO_PVP

FINALIZAR_PVP:
    CALL FINALIZAR_JOGO
    POP SI
    POP DX
    POP CX
    POP BX
    POP AX
    RET
JOGO_PVP ENDP

; ========== MODO PLAYER VS IA ==========
JOGO_PV_IA PROC
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX
    PUSH SI
    
CICLO_PV_IA:
    CALL IMPRIMIR_TABULEIRO
    CALL EXIBIR_TURNO_ATUAL
    CALL LER_JOGADA
    CALL VALIDAR_JOGADA
    JC JOGADA_INVALIDA_PV_IA

    CALL ATUALIZAR_MATRIZ
    CALL VERIFICAR_ESTADO_JOGO
    TEST CL, CL
    JNZ FINALIZAR_COM_RESULTADO
    CALL ALTERNAR_JOGADOR

TURNO_IA:
    CALL ESCOLHER_JOGADA_IA ; *** IA FUNCIONAL DO CÓDIGO 1 ***
    CALL VALIDAR_JOGADA
    JNC ATUALIZAR_IA
    JMP TURNO_IA

ATUALIZAR_IA:
    CALL ATUALIZAR_MATRIZ
    CALL VERIFICAR_ESTADO_JOGO
    TEST CL, CL
    JNZ FINALIZAR_COM_RESULTADO
    CALL ALTERNAR_JOGADOR
    JMP CICLO_PV_IA

FINALIZAR_COM_RESULTADO:
    CALL EXIBIR_RESULTADO_FINAL

FINALIZAR_PV_IA:
    CALL FINALIZAR_JOGO
    POP SI
    POP DX
    POP CX
    POP BX
    POP AX
    RET

JOGADA_INVALIDA_PV_IA:
    CALL TRATAR_ERRO_JOGADA
    JMP CICLO_PV_IA
JOGO_PV_IA ENDP

; ========== LÓGICA DO JOGO ==========
EXIBIR_TURNO_ATUAL PROC
    MOV AL, JOGADOR_ATUAL
    MOV BX, 30
    MOV [TURNO+BX], AL
    MOV AH, 9
    LEA DX, TURNO
    INT 21H
    RET
EXIBIR_TURNO_ATUAL ENDP

LER_JOGADA PROC
    MOV AH, 1
    INT 21H
    RET
LER_JOGADA ENDP

VALIDAR_JOGADA PROC
    CMP AL, '1'
    JB JOGADA_INVALIDA_VAL
    CMP AL, '9'
    JA JOGADA_INVALIDA_VAL
    CALL VERIFICAR_CASA_LIVRE
    CMP CL, 0
    JE JOGADA_INVALIDA_VAL
    CLC
    RET

JOGADA_INVALIDA_VAL:
    STC
    RET
VALIDAR_JOGADA ENDP

TRATAR_ERRO_JOGADA PROC
    MOV AH, 9
    CMP AL, '1'
    JB NUMERO_INVALIDO_ERR
    CMP AL, '9'
    JA NUMERO_INVALIDO_ERR
    LEA DX, CASAOCUPADA
    INT 21H
    RET

NUMERO_INVALIDO_ERR:
    LEA DX, NUMEROINVALIDO
    INT 21H
    RET
TRATAR_ERRO_JOGADA ENDP

VERIFICAR_CASA_LIVRE PROC
    PUSHF
    PUSH AX
    PUSH BX
    PUSH SI
    XOR BX, BX
    XOR SI, SI
    XOR CX, CX
    AND AL, 0FH

    CMP AL, 1
    JE VER_POS1
    CMP AL, 2
    JE VER_POS2
    CMP AL, 3
    JE VER_POS3
    CMP AL, 4
    JE VER_POS4
    CMP AL, 5
    JE VER_POS5
    CMP AL, 6
    JE VER_POS6
    CMP AL, 7
    JE VER_POS7
    CMP AL, 8
    JE VER_POS8
    CMP AL, 9
    JE VER_POS9

VER_POS1:
    MOV AH, MATRIZ[BX][SI]
    JMP VERIFICAR_SIMBOLO_LIVRE

VER_POS2:
    MOV SI, 1
    MOV AH, MATRIZ[BX][SI]
    JMP VERIFICAR_SIMBOLO_LIVRE

VER_POS3:
    MOV SI, 2
    MOV AH, MATRIZ[BX][SI]
    JMP VERIFICAR_SIMBOLO_LIVRE

VER_POS4:
    MOV BX, 3
    MOV AH, MATRIZ[BX][SI]
    JMP VERIFICAR_SIMBOLO_LIVRE

VER_POS5:
    MOV BX, 3
    MOV SI, 1
    MOV AH, MATRIZ[BX][SI]
    JMP VERIFICAR_SIMBOLO_LIVRE

VER_POS6:
    MOV BX, 3
    MOV SI, 2
    MOV AH, MATRIZ[BX][SI]
    JMP VERIFICAR_SIMBOLO_LIVRE

VER_POS7:
    MOV BX, 6
    MOV AH, MATRIZ[BX][SI]
    JMP VERIFICAR_SIMBOLO_LIVRE

VER_POS8:
    MOV BX, 6
    MOV SI, 1
    MOV AH, MATRIZ[BX][SI]
    JMP VERIFICAR_SIMBOLO_LIVRE

VER_POS9:
    MOV BX, 6
    MOV SI, 2
    MOV AH, MATRIZ[BX][SI]

VERIFICAR_SIMBOLO_LIVRE:
    CMP AH, 'X'
    JE CASA_OCUPADA_LIVRE
    CMP AH, 'O'
    JE CASA_OCUPADA_LIVRE
    MOV CL, 1
    JMP FIM_VERIFICACAO_LIVRE

CASA_OCUPADA_LIVRE:
    MOV CL, 0

FIM_VERIFICACAO_LIVRE:
    POP SI
    POP BX
    POP AX
    POPF
    RET
VERIFICAR_CASA_LIVRE ENDP

ATUALIZAR_MATRIZ PROC
    PUSH AX
    PUSH BX 
    PUSH CX
    PUSH SI
    PUSHF
    XOR BX, BX
    XOR SI, SI
    MOV CL, JOGADOR_ATUAL
    AND AL, 0FH

    CMP AL, 1
    JE ATUALIZAR_POS1
    CMP AL, 2
    JE ATUALIZAR_POS2
    CMP AL, 3
    JE ATUALIZAR_POS3
    CMP AL, 4
    JE ATUALIZAR_POS4
    CMP AL, 5
    JE ATUALIZAR_POS5
    CMP AL, 6
    JE ATUALIZAR_POS6
    CMP AL, 7
    JE ATUALIZAR_POS7
    CMP AL, 8
    JE ATUALIZAR_POS8
    CMP AL, 9
    JE ATUALIZAR_POS9

ATUALIZAR_POS1:
    MOV MATRIZ[BX][SI], CL
    JMP FIM_ATUALIZACAO

ATUALIZAR_POS2:
    MOV SI, 1
    MOV MATRIZ[BX][SI], CL
    JMP FIM_ATUALIZACAO

ATUALIZAR_POS3:
    MOV SI, 2
    MOV MATRIZ[BX][SI], CL
    JMP FIM_ATUALIZACAO

ATUALIZAR_POS4:
    MOV BX, 3
    MOV MATRIZ[BX][SI], CL
    JMP FIM_ATUALIZACAO

ATUALIZAR_POS5:
    MOV BX, 3
    MOV SI, 1
    MOV MATRIZ[BX][SI], CL
    JMP FIM_ATUALIZACAO

ATUALIZAR_POS6:
    MOV BX, 3
    MOV SI, 2
    MOV MATRIZ[BX][SI], CL
    JMP FIM_ATUALIZACAO

ATUALIZAR_POS7:
    MOV BX, 6
    MOV MATRIZ[BX][SI], CL
    JMP FIM_ATUALIZACAO

ATUALIZAR_POS8:
    MOV BX, 6
    MOV SI, 1
    MOV MATRIZ[BX][SI], CL
    JMP FIM_ATUALIZACAO

ATUALIZAR_POS9:
    MOV BX, 6
    MOV SI, 2
    MOV MATRIZ[BX][SI], CL

FIM_ATUALIZACAO:
    INC JOGADAS_FEITAS
    POPF
    POP SI
    POP CX
    POP BX
    POP AX
    RET
ATUALIZAR_MATRIZ ENDP

ALTERNAR_JOGADOR PROC
    PUSH AX
    PUSHF
    MOV AL, JOGADOR_ATUAL
    CMP AL, 'X'
    JE TROCAR_PARA_O
    MOV JOGADOR_ATUAL, 'X'
    JMP FIM_TROCA_JOGADOR
    
TROCAR_PARA_O:
    MOV JOGADOR_ATUAL, 'O'

FIM_TROCA_JOGADOR:
    POPF
    POP AX
    RET
ALTERNAR_JOGADOR ENDP

; ========== INTELIGÊNCIA ARTIFICIAL (DO CÓDIGO 1 - FUNCIONAL) ==========
ESCOLHER_JOGADA_IA PROC
    ; IA escolhe jogada - VERSÃO FUNCIONAL DO CÓDIGO 1
    PUSH DX
    PUSH CX
    PUSH BX
    PUSH SI

    MOV AL, JOGADAS_FEITAS
    CMP AL, 3
    JAE ESCOLHAPENSADA
    JMP ESCOLHAALEATORIA

ESCOLHAPENSADA:
    ; Verifica linhas para vitória/defesa
    XOR BX, BX
CHECA_PROXIMA_LINHA:
    XOR DX, DX
    MOV CX, 3
    XOR SI, SI
CHECA_LINHA_ATUAL:
    MOV AL, MATRIZ[BX][SI]
    TESTA_CASA_IA AL      ; USA O MACRO FUNCIONAL
    INC SI 
    LOOP CHECA_LINHA_ATUAL
    
    CMP DH, 2            ; 2 O? → chance de vitória
    JNE VER_O_LINHA
    JMP DESCOBRIU_LINHA
    
VER_O_LINHA:
    CMP DL, 2            ; 2 X? → precisa bloquear
    JNE PROXIMA_LINHA
    JMP DESCOBRIU_LINHA
    
PROXIMA_LINHA:
    ADD BX, 3
    CMP BX, 6
    JBE CHECA_PROXIMA_LINHA
    
    ; Verifica colunas
    XOR SI, SI
CHECA_PROXIMA_COLUNA:
    XOR DX, DX
    MOV CX, 3
    XOR BX, BX
CHECA_COLUNA_ATUAL:
    MOV AL, MATRIZ[BX][SI]
    TESTA_CASA_IA AL
    ADD BX, 3
    LOOP CHECA_COLUNA_ATUAL

    CMP DH, 2            ; 2 O? → chance de vitória
    JNE VER_O_COLUNA
    JMP DESCOBRIU_COLUNA
    
VER_O_COLUNA:
    CMP DL, 2            ; 2 X? → precisa bloquear
    JNE PROXIMA_COLUNA
    JMP DESCOBRIU_COLUNA
    
PROXIMA_COLUNA:
    INC SI
    CMP SI, 3
    JNZ CHECA_PROXIMA_COLUNA

    ; Verifica diagonal principal
    XOR DX, DX
    XOR BX, BX
    XOR SI, SI
    MOV CX, 3
PRIMEIRA_DIAGONAL:
    MOV AL, MATRIZ[BX][SI]
    TESTA_CASA_IA AL
    ADD BX, 3
    INC SI
    LOOP PRIMEIRA_DIAGONAL
    
    CMP DH, 2            ; 2 O? → chance de vitória
    JNE VER_O_DIAGONAL1
    JMP DESCOBRIU_DIAGONAL1
    
VER_O_DIAGONAL1:
    CMP DL, 2            ; 2 X? → precisa bloquear
    JNE PROXIMA_DIAGONAL
    JMP DESCOBRIU_DIAGONAL1

PROXIMA_DIAGONAL:
    ; Verifica diagonal secundária
    XOR DX, DX
    XOR BX, BX
    MOV SI, 2
    MOV CX, 3
SEGUNDA_DIAGONAL:
    MOV AL, MATRIZ[BX][SI]
    TESTA_CASA_IA AL
    ADD BX, 3
    DEC SI
    LOOP SEGUNDA_DIAGONAL

    CMP DH, 2            ; 2 O? → chance de vitória
    JNE VER_O_DIAGONAL2
    JMP DESCOBRIU_DIAGONAL2
    
VER_O_DIAGONAL2:
    CMP DL, 2            ; 2 X? → precisa bloquear
    JNE ESCOLHAALEATORIA
    JMP DESCOBRIU_DIAGONAL2
    
; Encontrou linha com chance
DESCOBRIU_LINHA:
    XOR SI, SI
    MOV CX, 3
CHECA_CASA_LINHA:
    MOV AL, MATRIZ[BX][SI]
    CMP AL, '9'          ; ≤ '9'? → vazia
    JBE ESCOLHAFEITA
    INC SI 
    LOOP CHECA_CASA_LINHA 
    JMP PROXIMA_LINHA
    
; Encontrou coluna com chance
DESCOBRIU_COLUNA:
    XOR BX, BX
    MOV CX, 3
CHECA_CASA_COLUNA:
    MOV AL, MATRIZ[BX][SI]
    CMP AL, '9'          ; ≤ '9'? → vazia
    JBE ESCOLHAFEITA
    ADD BX, 3
    LOOP CHECA_CASA_COLUNA
    JMP PROXIMA_COLUNA
    
; Encontrou diagonal principal com chance
DESCOBRIU_DIAGONAL1:
    XOR BX, BX
    XOR SI, SI
    MOV CX, 3
CHECA_CASA_DIAGONAL1:
    MOV AL, MATRIZ[BX][SI]
    CMP AL, '9'          ; ≤ '9'? → vazia
    JBE ESCOLHAFEITA
    ADD BX, 3
    INC SI
    LOOP CHECA_CASA_DIAGONAL1
    JMP PROXIMA_DIAGONAL
    
; Encontrou diagonal secundária com chance
DESCOBRIU_DIAGONAL2:
    XOR BX, BX
    MOV SI, 2
    MOV CX, 3
CHECA_CASA_DIAGONAL2:
    MOV AL, MATRIZ[BX][SI]
    CMP AL, '9'          ; ≤ '9'? → vazia
    JBE ESCOLHAFEITA
    ADD BX, 3
    DEC SI
    LOOP CHECA_CASA_DIAGONAL2
    JMP ESCOLHAALEATORIA
        
ESCOLHAFEITA:
    POP SI
    POP BX
    POP CX
    POP DX
    RET

ESCOLHAALEATORIA:
    MOV AH, 2CH
    INT 21H
    MOV AL, DL
    XOR AH, AH
    MOV CL, 9
    DIV CL
    INC AH
    MOV AL, AH
    OR AL, 30H
    JMP ESCOLHAFEITA
ESCOLHER_JOGADA_IA ENDP

; ========== VERIFICAÇÃO DE VITÓRIA/EMPATE ==========
VERIFICAR_ESTADO_JOGO PROC
    PUSH BX
    PUSH SI
    PUSH AX
    PUSH DX
    XOR BX, BX
    XOR SI, SI
    XOR CL, CL
    MOV AL, JOGADOR_ATUAL

    CALL VERIFICAR_LINHA_VITORIA
    JC VITORIA_ENCONTRADA_ESTADO
    CALL VERIFICAR_COLUNA_VITORIA
    JC VITORIA_ENCONTRADA_ESTADO
    CALL VERIFICAR_DIAGONAL_VITORIA
    JC VITORIA_ENCONTRADA_ESTADO

    MOV AL, JOGADAS_FEITAS
    CMP AL, 9
    JB FIM_VERIFICACAO_ESTADO
    MOV CL, 2

VITORIA_ENCONTRADA_ESTADO:
    MOV CL, 1

FIM_VERIFICACAO_ESTADO:
    POP DX
    POP AX
    POP SI
    POP BX
    RET
VERIFICAR_ESTADO_JOGO ENDP

VERIFICAR_LINHA_VITORIA PROC
    PUSH BX
    PUSH SI
    XOR BX, BX
    XOR SI, SI
    CALL VERIFICAR_TRES_POSICOES
    JC VITORIA_LINHA_VER
    MOV BX, 3
    XOR SI, SI
    CALL VERIFICAR_TRES_POSICOES
    JC VITORIA_LINHA_VER
    MOV BX, 6
    XOR SI, SI
    CALL VERIFICAR_TRES_POSICOES
    JC VITORIA_LINHA_VER
    CLC
    JMP FIM_VERIFICAR_LINHA_VER

VITORIA_LINHA_VER:
    STC

FIM_VERIFICAR_LINHA_VER:
    POP SI
    POP BX
    RET
VERIFICAR_LINHA_VITORIA ENDP

VERIFICAR_COLUNA_VITORIA PROC
    PUSH BX
    PUSH SI
    XOR BX, BX
    XOR SI, SI
    CALL VERIFICAR_TRES_POSICOES_COLUNA
    JC VITORIA_COLUNA_VER
    XOR BX, BX
    MOV SI, 1
    CALL VERIFICAR_TRES_POSICOES_COLUNA
    JC VITORIA_COLUNA_VER
    XOR BX, BX
    MOV SI, 2
    CALL VERIFICAR_TRES_POSICOES_COLUNA
    JC VITORIA_COLUNA_VER
    CLC
    JMP FIM_VERIFICAR_COLUNA_VER

VITORIA_COLUNA_VER:
    STC

FIM_VERIFICAR_COLUNA_VER:
    POP SI
    POP BX
    RET
VERIFICAR_COLUNA_VITORIA ENDP

VERIFICAR_DIAGONAL_VITORIA PROC
    PUSH BX
    PUSH SI
    XOR BX, BX
    XOR SI, SI
    CALL VERIFICAR_TRES_POSICOES_DIAGONAL
    JC VITORIA_DIAGONAL_VER
    XOR BX, BX
    MOV SI, 2
    CALL VERIFICAR_TRES_POSICOES_DIAGONAL_INVERSA
    JC VITORIA_DIAGONAL_VER
    CLC
    JMP FIM_VERIFICAR_DIAGONAL_VER

VITORIA_DIAGONAL_VER:
    STC

FIM_VERIFICAR_DIAGONAL_VER:
    POP SI
    POP BX
    RET
VERIFICAR_DIAGONAL_VITORIA ENDP

VERIFICAR_TRES_POSICOES PROC
    MOV DL, MATRIZ[BX][SI]
    CMP AL, DL
    JNE FALHA_TRES_POSICOES
    INC SI
    MOV DL, MATRIZ[BX][SI]
    CMP AL, DL
    JNE FALHA_TRES_POSICOES
    INC SI
    MOV DL, MATRIZ[BX][SI]
    CMP AL, DL
    JNE FALHA_TRES_POSICOES
    STC
    RET

FALHA_TRES_POSICOES:
    CLC
    RET
VERIFICAR_TRES_POSICOES ENDP

VERIFICAR_TRES_POSICOES_COLUNA PROC
    MOV DL, MATRIZ[BX][SI]
    CMP AL, DL
    JNE FALHA_TRES_COLUNA
    ADD BX, 3
    MOV DL, MATRIZ[BX][SI]
    CMP AL, DL
    JNE FALHA_TRES_COLUNA
    ADD BX, 3
    MOV DL, MATRIZ[BX][SI]
    CMP AL, DL
    JNE FALHA_TRES_COLUNA
    STC
    RET

FALHA_TRES_COLUNA:
    CLC
    RET
VERIFICAR_TRES_POSICOES_COLUNA ENDP

VERIFICAR_TRES_POSICOES_DIAGONAL PROC
    MOV DL, MATRIZ[BX][SI]
    CMP AL, DL
    JNE FALHA_TRES_DIAGONAL
    ADD BX, 3
    INC SI
    MOV DL, MATRIZ[BX][SI]
    CMP AL, DL
    JNE FALHA_TRES_DIAGONAL
    ADD BX, 3
    INC SI
    MOV DL, MATRIZ[BX][SI]
    CMP AL, DL
    JNE FALHA_TRES_DIAGONAL
    STC
    RET

FALHA_TRES_DIAGONAL:
    CLC
    RET
VERIFICAR_TRES_POSICOES_DIAGONAL ENDP

VERIFICAR_TRES_POSICOES_DIAGONAL_INVERSA PROC
    MOV DL, MATRIZ[BX][SI]
    CMP AL, DL
    JNE FALHA_TRES_DIAGONAL_INVERSA
    ADD BX, 3
    DEC SI
    MOV DL, MATRIZ[BX][SI]
    CMP AL, DL
    JNE FALHA_TRES_DIAGONAL_INVERSA
    ADD BX, 3
    DEC SI
    MOV DL, MATRIZ[BX][SI]
    CMP AL, DL
    JNE FALHA_TRES_DIAGONAL_INVERSA
    STC
    RET

FALHA_TRES_DIAGONAL_INVERSA:
    CLC
    RET
VERIFICAR_TRES_POSICOES_DIAGONAL_INVERSA ENDP

; ========== FINALIZAÇÃO ==========
FINALIZAR_JOGO PROC
    MOV AH, 2
    MOV DL, 10
    INT 21H
    MOV AH, 9
    LEA DX, CLIQUE
    INT 21H
    MOV AH, 1
    INT 21H
    CALL REINICIAR_MATRIZ
    RET
FINALIZAR_JOGO ENDP

REINICIAR_MATRIZ PROC
    PUSH AX
    PUSH BX
    PUSH SI
    MOV MATRIZ[0], '1'
    MOV MATRIZ[1], '2' 
    MOV MATRIZ[2], '3'
    MOV MATRIZ[3], '4'
    MOV MATRIZ[4], '5'
    MOV MATRIZ[5], '6'
    MOV MATRIZ[6], '7'
    MOV MATRIZ[7], '8'
    MOV MATRIZ[8], '9'
    MOV JOGADAS_FEITAS, 0
    MOV JOGADOR_ATUAL, 'X'
    POP SI
    POP BX
    POP AX
    RET
REINICIAR_MATRIZ ENDP

END MAIN
